CREATE TABLE USER_FM(
ID_USER NUMBER,
CONSTRAINT USER_ID PRIMARY KEY(ID_USER),
FIRST_NAME NVARCHAR2(50) NOT NULL,
LAST_NAME NVARCHAR2(50) NOT NULL,
PHONE NVARCHAR2(50) NOT NULL,
COUNTRY NVARCHAR2(50),
CITY NVARCHAR2(50),
AGE NUMBER,
DATE_REGISTRATED DATE,
LAST_DATE_ACTIVATED DATE,
RELATIONSHIP_STATUS NVARCHAR2(50), CHECK (RELATIONSHIP_STATUS IN('Sinle','Married', '')),
RELIGION NVARCHAR2(50), CHECK(RELIGION IN('Christian', 'Catholic', 'Muslim', '')),
SCHOOL NVARCHAR2(50),
UNIVERSITY NVARCHAR2(50)
);

ALTER TABLE USER_FM
ADD MES_RECEIVED  NUMBER;

ALTER TABLE USER_FM
ADD MES_SEND  NUMBER;

ALTER TABLE USER_FM
ADD CONSTRAINT US_MES_SEND_FK FOREIGN KEY(MES_SEND) REFERENCES MESSAGE(ID_MS);

ALTER TABLE USER_FM
ADD CONSTRAINT US_MES_RCV_FK FOREIGN KEY(MES_RECEIVED) REFERENCES MESSAGE(ID_MS);

ALTER TABLE USER_FM ADD EMAIL NVARCHAR2(20) NOT NULL;
ALTER TABLE USER_FM ADD PASSWORD NVARCHAR2(20) NOT NULL;

ALTER TABLE USER_FM ADD  LOGIN_STATUS NVARCHAR2(20) DEFAULT 'LOGOUT';
ALTER TABLE USER_FM ADD CONSTRAINT ST_CHECK CHECK(LOGIN_STATUS IN ('LOGOUT', 'LOGIN', 'SUSPEND'));
