CREATE TABLE POST(
ID_POST  NUMBER NOT NULL,
CONSTRAINT POST_PK PRIMARY KEY(ID_POST),
MESSAGE NVARCHAR2(150),
DATE_POSTED DATE,
LOCATION NVARCHAR2(30),
USER_POSTED_ID NUMBER,
CONSTRAINT POST_US_FK FOREIGN KEY (USER_POSTED_ID) REFERENCES USER_FM(ID_USER) ON DELETE SET NULL,
USER_PAGE_POSTED_ID NUMBER,
CONSTRAINT POST_US_PG_POST_FK FOREIGN KEY (USER_PAGE_POSTED_ID) REFERENCES USER_FM(ID_USER) ON DELETE SET NULL);
