CREATE TABLE MESSAGE(
ID_MS NUMBER,
CONSTRAINT MS_PK PRIMARY KEY(ID_MS),
TEXT NVARCHAR2(150),
DATE_SENT DATE,
DATE_READ DATE,
USER_FROM NUMBER,
CONSTRAINT  US_FR_MSG_FK FOREIGN KEY (USER_FROM) REFERENCES USER_FM(ID_USER),
USER_TO NUMBER,
CONSTRAINT US_TO_MSG_FK FOREIGN KEY(USER_TO) REFERENCES USER_FM(ID_USER)
);